<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSdax8X9\Glpi_Kernel_KernelProductionContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSdax8X9/Glpi_Kernel_KernelProductionContainer.php') {
    touch(__DIR__.'/ContainerSdax8X9.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionContainer::class, false)) {
    \class_alias(\ContainerSdax8X9\Glpi_Kernel_KernelProductionContainer::class, Glpi_Kernel_KernelProductionContainer::class, false);
}

return new \ContainerSdax8X9\Glpi_Kernel_KernelProductionContainer([
    'container.build_hash' => 'Sdax8X9',
    'container.build_id' => '237a9004',
    'container.build_time' => 1772627042,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSdax8X9');
