-- PLANO DE ROLLBACK GERADO ANTES DA MUDANÇA. NÃO EXECUTAR SEM APROVAÇÃO.
BEGIN;
REVOKE triagem_runtime FROM "triagem_app";
ALTER ROLE "triagem_app" NOSUPERUSER NOCREATEROLE NOCREATEDB NOREPLICATION NOBYPASSRLS;
ALTER TABLE "public"."avaliacao_auto_confirmacoes" OWNER TO "triagem_user";
ALTER TABLE "public"."avaliacoes_humanas" OWNER TO "triagem_user";
ALTER TABLE "public"."dataset_controle" OWNER TO "triagem_user";
ALTER TABLE "public"."experimentos_avaliacao" OWNER TO "triagem_user";
ALTER TABLE "public"."fila_ia_controle" OWNER TO "triagem_user";
ALTER TABLE "public"."fila_ia_dead_letter" OWNER TO "triagem_user";
ALTER TABLE "public"."fila_ia_metricas" OWNER TO "triagem_user";
ALTER TABLE "public"."ia_decisoes" OWNER TO "triagem_user";
ALTER TABLE "public"."ia_tentativas_modelo" OWNER TO "triagem_user";
ALTER TABLE "public"."metricas_diarias_automacao" OWNER TO "triagem_user";
ALTER VIEW "public"."metricas_ia_duplicidade_v9" OWNER TO "triagem_user";
ALTER TABLE "public"."metricas_prompt_version" OWNER TO "triagem_user";
ALTER TABLE "public"."metricas_workflow_performance" OWNER TO "triagem_user";
ALTER TABLE "public"."resumos_executivos_ia" OWNER TO "triagem_user";
ALTER TABLE "public"."tickets_processados" OWNER TO "triagem_user";
ALTER VIEW "public"."v_aguardando_fiscal" OWNER TO "triagem_user";
ALTER VIEW "public"."v_resumo_workflow" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_auc_classificacao" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_auc_deduplicacao" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_average_precision_classificacao" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_average_precision_deduplicacao" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_brier_classificacao" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_candidatos_automacao_total" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_chamados_travados" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_comparacao_prompt_modelo" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_confianca_ia" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_dataset_controle_resultados" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_decisoes_classificacao" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_decisoes_confirmatorias_elegiveis" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_decisoes_deduplicacao" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_decisoes_deduplicacao_desafio" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_erros_ia" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_erros_ia_sem_dead_letter" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_gabarito_final" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_kpi_classificacao" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_kpi_duplicidade" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_kpi_geral_automacao" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_log_loss_classificacao" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_log_loss_deduplicacao" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_matriz_confusao_classificacao" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_metricas_assertividade_classificacao" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_metricas_deduplicacao" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_metricas_deduplicacao_desafio" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_pr_classificacao" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_pr_deduplicacao" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_proveniencia_gateway_ia" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_recall_candidatos_deduplicacao" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_risco_cobertura_classificacao" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_roc_classificacao" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_roc_deduplicacao" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_scores_classificacao" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_scores_deduplicacao" OWNER TO "triagem_user";
ALTER VIEW "public"."vw_tempo_execucao_workflow" OWNER TO "triagem_user";
ALTER TABLE "public"."workflow_eventos" OWNER TO "triagem_user";
COMMIT;
-- Após rollback: revalidar saúde, permissões, fila, DLQ e um cenário sombra.
