
version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: glpi-db
    restart: unless-stopped
  
    environment:
      MYSQL_ROOT_PASSWORD: RootPassGLPI2024
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi_usero
      MYSQL_PASSWORD: GlpiPass2024
   
    volumes:
      - glpi-db-data:/var/lib/mysql # armazena os arquivos do banco de dados MariaDB
    
    networks:
      - glpi-net # rede o container se conecta

  glpi:
    image: diouxx/glpi:latest #vem com mock data
 
    container_name: glpi-app
  
    restart: unless-stopped

    ports:
      - '8080:80' 
#http://localhost:8080
#USER: glpi
#PASS: admin
 
    environment:
     
      TIMEZONE: America/Sao_Paulo

    volumes:
      # glpi-data armazena arquivos e configurações do GLPI 
      - glpi-data:/var/www/html/glpi
  
    # GLPI inicia apos bd
    depends_on:
      - mariadb 
    networks:
      - glpi-net
    extra_hosts:
      - 'host.docker.internal:host-gateway' # permite apontar SMTP para Mailpit no host

volumes:
  glpi-db-data: # glpi-db-data para armazenar os arquivos do MariaDB
  glpi-data:


networks:
  # chama glpi-net em modo bridge, permitindo comunicação entre containers e acesso ao host
  glpi-net:
    driver: bridge